# Creating all the artists
michael_jackson = Artist.create(name: "Michael Jackson")
lady_gaga       = Artist.create(name: "Lady Gaga")
beatles         = Artist.create(name: "The Beatles")
oasis           = Artist.create(name: "Oasis")
daft_punk       = Artist.create(name: "Daft Punk")
kaz_james       = Artist.create(name: "Kaz James")
rampa           = Artist.create(name: "Rampa")
dixon           = Artist.create(name: "Dixon")
ame             = Artist.create(name: "Ame")
tom_trago       = Artist.create(name: "Tom Trago")
justin_hurwitz  = Artist.create(name: "Justin Hurwitz")
hans            = Artist.create(name: "Hans Zimmer")
drake           = Artist.create(name: "Drake")
cent            = Artist.create(name: "50 Cent")
fleetwood       = Artist.create(name: "Fleetwood Mac")
yann            = Artist.create(name: "Yann Tiersen")
nino            = Artist.create(name: "Nino Rota")
cerrone         = Artist.create(name: "Cerrone")
greg            = Artist.create(name: "DJ Gregory")
soha            = Artist.create(name: "Soha")
crazy_p         = Artist.create(name: "Crazy P")
coeo            = Artist.create(name: "Coeo")
moby            = Artist.create(name: "Moby")
prince          = Artist.create(name: "Prince")
butch           = Artist.create(name: "Butch")
nina            = Artist.create(name: "Nina Kraviz")
kink            = Artist.create(name: "Kink")
franck          = Artist.create(name: "Franck Roger")
trikk           = Artist.create(name: "Trikk")
kenny           = Artist.create(name: "Kenny Dope")
frank           = Artist.create(name: "Frank Sinatra")


# Creating all the genres (not many of them)
pop             = Genre.create(name: "Pop")
house           = Genre.create(name: "House")
funk            = Genre.create(name: "Funk / Soul")
hip             = Genre.create(name: "Hip Hop")
rock            = Genre.create(name: "Rock")
electro         = Genre.create(name: "Electronic")
cinema          = Genre.create(name: "Cinematic")
minimal         = Genre.create(name: "Minimal House")

# And now for the songs
Song.create(name: "Thriller", artist: michael_jackson, genre: pop)
Song.create(name: "Smooth Criminal", artist: michael_jackson, genre: pop)
Song.create(name: "Billie Jean", artist: michael_jackson, genre: pop)
Song.create(name: "Rock My World", artist: michael_jackson, genre: pop)
Song.create(name: "Black Or White", artist: michael_jackson, genre: pop)
Song.create(name: "Love Never Felt So Good", artist: michael_jackson, genre: pop)
Song.create(name: "Shallow", artist: lady_gaga, genre: cinema)
Song.create(name: "Bad Romance", artist: lady_gaga, genre: pop)
Song.create(name: "Just Dance", artist: lady_gaga, genre: pop)
Song.create(name: "Poker Face", artist: lady_gaga, genre: pop)
Song.create(name: "Alejandro", artist: lady_gaga, genre: pop)
Song.create(name: "Telephone", artist: lady_gaga, genre: pop)
Song.create(name: "Help!", artist: beatles, genre: pop)
Song.create(name: "Love Me Do", artist: beatles, genre: pop)
Song.create(name: "Here Comes The Sun", artist: beatles, genre: pop)
Song.create(name: "Come Together", artist: beatles, genre: pop)
Song.create(name: "Yesterday", artist: beatles, genre: pop)
Song.create(name: "Let It Be", artist: beatles, genre: pop)
Song.create(name: "Hey Jude", artist: beatles, genre: pop)
Song.create(name: "Sgt Pepper Lonely Hearts Club Band", artist: beatles, genre: rock)
Song.create(name: "While My Guitar Gently Weeps", artist: beatles, genre: pop)
Song.create(name: "Honey Pie", artist: beatles, genre: pop)
Song.create(name: "When I'm 64", artist: beatles, genre: pop)
Song.create(name: "Eleanor Rigby", artist: beatles, genre: pop)
Song.create(name: "She Loves You", artist: beatles, genre: rock)
Song.create(name: "Champagne Supernova", artist: oasis, genre: rock)
Song.create(name: "Wonderwall", artist: oasis, genre: rock)
Song.create(name: "Don't Look Back In Anger", artist: oasis, genre: rock)
Song.create(name: "Stop Crying Your Heart Out", artist: oasis, genre: rock)
Song.create(name: "Get Lucky", artist: daft_punk, genre: pop)
Song.create(name: "One More Time", artist: daft_punk, genre: electro)
Song.create(name: "Da Funk", artist: daft_punk, genre: electro)
Song.create(name: "Lose Yourself To Dance", artist: daft_punk, genre: pop)
Song.create(name: "Instant Crush", artist: daft_punk, genre: pop)
Song.create(name: "Fresh", artist: daft_punk, genre: electro)
Song.create(name: "Veridis Quo", artist: daft_punk, genre: electro)
Song.create(name: "Give Life Back To Music", artist: daft_punk, genre: pop)
Song.create(name: "Through Your Love", artist: kaz_james, genre: house)
Song.create(name: "Twisted", artist: kaz_james, genre: house)
Song.create(name: "Paradise", artist: kaz_james, genre: house)
Song.create(name: "Muye", artist: rampa, genre: house)
Song.create(name: "Tell Me Are We", artist: rampa, genre: house)
Song.create(name: "Far Away Place", artist: rampa, genre: house)
Song.create(name: "Sunday", artist: rampa, genre: house)
Song.create(name: "Cover Me", artist: dixon, genre: house)
Song.create(name: "Toukan", artist: dixon, genre: house)
Song.create(name: "Rej", artist: ame, genre: house)
Song.create(name: "No War", artist: ame, genre: house)
Song.create(name: "Turn Around", artist: ame, genre: house)
Song.create(name: "The Line", artist: ame, genre: house)
Song.create(name: "Hidden Heart Of Gold", artist: tom_trago, genre: minimal)
Song.create(name: "Use Me Again", artist: tom_trago, genre: house)
Song.create(name: "Epilogue", artist: justin_hurwitz, genre: cinema)
Song.create(name: "City Of Stars", artist: justin_hurwitz, genre: cinema)
Song.create(name: "The Landing", artist: justin_hurwitz, genre: cinema)
Song.create(name: "Quarantine", artist: justin_hurwitz, genre: cinema)
Song.create(name: "Audition", artist: justin_hurwitz, genre: cinema)
Song.create(name: "Rise", artist: hans, genre: cinema)
Song.create(name: "Chevaliers De Sangreal", artist: hans, genre: cinema)
Song.create(name: "Cornfield Chase", artist: hans, genre: cinema)
Song.create(name: "Stay", artist: hans, genre: cinema)
Song.create(name: "Time", artist: hans, genre: cinema)
Song.create(name: "Now We Are Free", artist: hans, genre: cinema)
Song.create(name: "Oogway Ascends", artist: hans, genre: cinema)
Song.create(name: "Davy Jones", artist: hans, genre: cinema)
Song.create(name: "God's Plan", artist: drake, genre: hip)
Song.create(name: "Passionfruit", artist: drake, genre: house)
Song.create(name: "One Dance", artist: drake, genre: hip)
Song.create(name: "Nice For What", artist: drake, genre: hip)
Song.create(name: "In My Feelings", artist: drake, genre: hip)
Song.create(name: "LOYAL", artist: drake, genre: hip)
Song.create(name: "Fuckin' Problems", artist: drake, genre: hip)
Song.create(name: "Jumpman", artist: drake, genre: hip)
Song.create(name: "Started From The Bottom", artist: drake, genre: hip)
Song.create(name: "Fake Love", artist: drake, genre: hip)
Song.create(name: "Hotline Bling", artist: drake, genre: hip)
Song.create(name: "Walk It Talk It", artist: drake, genre: hip)
Song.create(name: "Trophies", artist: drake, genre: hip)
Song.create(name: "Forever", artist: drake, genre: hip)
Song.create(name: "Take Care", artist: drake, genre: hip)
Song.create(name: "Candy Shop", artist: cent, genre: hip)
Song.create(name: "In Da Club", artist: cent, genre: hip)
Song.create(name: "Hate It Or Love It", artist: cent, genre: hip)
Song.create(name: "Just A Lil Bit", artist: cent, genre: hip)
Song.create(name: "P.I.M.P.", artist: cent, genre: hip)
Song.create(name: "Rhiannon", artist: fleetwood, genre: pop)
Song.create(name: "The Chain", artist: fleetwood, genre: rock)
Song.create(name: "Go Your Own Way", artist: fleetwood, genre: rock)
Song.create(name: "Everywhere", artist: fleetwood, genre: pop)
Song.create(name: "Dreams", artist: fleetwood, genre: pop)
Song.create(name: "Landslide", artist: fleetwood, genre: pop)
Song.create(name: "Songbird", artist: fleetwood, genre: pop)
Song.create(name: "Keep Me There", artist: fleetwood, genre: pop)
Song.create(name: "La Valse D'Amelie", artist: yann, genre: cinema)
Song.create(name: "Cantine D'Une Autre Ete", artist: yann, genre: cinema)
Song.create(name: "Godfather Waltz", artist: nino, genre: cinema)
Song.create(name: "Cerrone's Paradise", artist: cerrone, genre: funk)
Song.create(name: "Supernature", artist: cerrone, genre: electro)
Song.create(name: "Got To Have Loving", artist: cerrone, genre: funk)
Song.create(name: "Give Me Love", artist: cerrone, genre: funk)
Song.create(name: "Balea", artist: greg, genre: house)
Song.create(name: "Elle", artist: greg, genre: house)
Song.create(name: "Don't Know Malendro", artist: greg, genre: funk)
Song.create(name: "Solaris", artist: greg, genre: house)
Song.create(name: "Attends 1", artist: greg, genre: house)
Song.create(name: "Canoa", artist: greg, genre: house)
Song.create(name: "S2", artist: greg, genre: house)
Song.create(name: "Les Enfants Du Bled", artist: soha, genre: house)
Song.create(name: "Like A Fool", artist: crazy_p, genre: funk)
Song.create(name: "Heartbreaker", artist: crazy_p, genre: funk)
Song.create(name: "Love The Way", artist: crazy_p, genre: funk)
Song.create(name: "Controversy", artist: prince, genre: pop)
Song.create(name: "1999", artist: prince, genre: pop)
Song.create(name: "Like It Is", artist: coeo, genre: funk)
Song.create(name: "Porcelain", artist: moby, genre: electro)
Song.create(name: "Why Does My Heart Feel So Bad?", artist: moby, genre: pop)
Song.create(name: "Natural Blues", artist: moby, genre: pop)
Song.create(name: "Extreme Ways", artist: moby, genre: cinema)
Song.create(name: "Flower", artist: moby, genre: pop)
Song.create(name: "We Are All Made Of Stars", artist: moby, genre: pop)
Song.create(name: "Lift Me Up", artist: moby, genre: pop)
Song.create(name: "James Bond Theme", artist: moby, genre: cinema)
Song.create(name: "Grace", artist: moby, genre: pop)
Song.create(name: "Lale", artist: butch, genre: house)
Song.create(name: "Desire", artist: butch, genre: house)
Song.create(name: "I'm Gonna Get You", artist: nina, genre: house)
Song.create(name: "I'm Week", artist: nina, genre: house)
Song.create(name: "Ghetto Kraviz", artist: nina, genre: house)
Song.create(name: "Valentine's Groove", artist: kink, genre: house)
Song.create(name: "Tropic", artist: kink, genre: minimal)
Song.create(name: "Perth", artist: kink, genre: minimal)
Song.create(name: "Raw", artist: kink, genre: minimal)
Song.create(name: "Soar", artist: kink, genre: minimal)
Song.create(name: "Samodiva", artist: kink, genre: minimal)
Song.create(name: "Organ", artist: kink, genre: minimal)
Song.create(name: "Too Blind To See", artist: franck, genre: minimal)
Song.create(name: "Rebirth", artist: franck, genre: minimal)
Song.create(name: "Movimento", artist: trikk, genre: house)
Song.create(name: "Vilara", artist: trikk, genre: house)
Song.create(name: "Ardente", artist: trikk, genre: house)
Song.create(name: "Concreto", artist: trikk, genre: house)
Song.create(name: "Devila", artist: trikk, genre: house)
Song.create(name: "Kunu", artist: trikk, genre: house)
Song.create(name: "Bela", artist: trikk, genre: house)
Song.create(name: "The Illout", artist: kenny, genre: minimal)
Song.create(name: "My Way", artist: frank, genre: pop)
Song.create(name: "Come Fly With Me", artist: frank, genre: pop)
Song.create(name: "Somethin' Stupid", artist: frank, genre: pop)
Song.create(name: "That's Life", artist: frank, genre: cinema)
Song.create(name: "Fly Me To The Moon", artist: frank, genre: pop)
Song.create(name: "I've Got The World On A String", artist: frank, genre: pop)
Song.create(name: "I've Got You Under My Skin", artist: frank, genre: pop)
Song.create(name: "Strangers In The Night", artist: frank, genre: pop)
Song.create(name: "Theme From New York, New York", artist: frank, genre: pop)
Song.create(name: "Chicago", artist: frank, genre: pop)
Song.create(name: "The Way You Look Tonight", artist: frank, genre: pop)
Song.create(name: "All The Way", artist: frank, genre: pop)
Song.create(name: "Nancy", artist: frank, genre: pop)
Song.create(name: "All Or Nothing At All", artist: frank, genre: pop)

# Let's create the users
nick   = User.create(name: "Nick")
ali    = User.create(name: "Ali")
dinno  = User.create(name: "Dinno")
skye   = User.create(name: "Skye")
sergio = User.create(name: "Sergio")
jo     = User.create(name: "Hoots")
dan    = User.create(name: "Dan")
john   = User.create(name: "John")
liv    = User.create(name: "Liv")
sam    = User.create(name: "Sam")

# Create the playlists now, (and who created them)
house_plist   = Playlist.create(name: "House",user_id: nick.id)
pop_plist     = Playlist.create(name: "Pop",user_id: sam.id)
rock_plist    = Playlist.create(name: "Rock",user_id: skye.id)
minimal_plist = Playlist.create(name: "Minimal House",user_id: nick.id)
hip_plist     = Playlist.create(name: "Hip Hop",user_id: dinno.id)
cinema_plist  = Playlist.create(name: "Cinematic",user_id: john.id)
electro_plist = Playlist.create(name: "Electronic",user_id: dan.id)
funk_plist    = Playlist.create(name: "Funk / Soul",user_id: nick.id)
summer        = Playlist.create(name: "Summer",user_id: nick.id)
newyears      = Playlist.create(name: "New Year's Eve",user_id: nick.id)
drakes        = Playlist.create(name: "Drake",user_id: nick.id)
sundaze       = Playlist.create(name: "Frank Sinatra Special",user_id: nick.id)

# Create the playlists of each genre and a couple others
drakes.add_songs_from_artist("Drake")
house_plist.add_songs_from_genre("House")
pop_plist.add_songs_from_genre("Pop")
rock_plist.add_songs_from_genre("Rock")
minimal_plist.add_songs_from_genre("Minimal House")
hip_plist.add_songs_from_genre("Hip Hop")
cinema_plist.add_songs_from_genre("Cinematic")
electro_plist.add_songs_from_genre("Electronic")
funk_plist.add_songs_from_genre("Funk / Soul")
sundaze.add_songs_from_artist("Frank Sinatra")
summer.add_songs_from_artist("DJ Gregory")
summer.add_songs_from_artist("Trikk")
summer.add_songs_from_artist("Dixon")
summer.add_songs_from_artist("Coeo")
summer.add_songs_from_artist("Crazy P")
newyears.add_songs_from_genre("Minimal House")
newyears.add_songs_from_genre("House")

# Create the Followings
Followings.create(user_id: nick.id, playlist_id: sundaze.id)
Followings.create(user_id: nick.id, playlist_id: funk_plist.id)
Followings.create(user_id: nick.id, playlist_id: house_plist.id)
Followings.create(user_id: nick.id, playlist_id: pop_plist.id)
Followings.create(user_id: nick.id, playlist_id: rock_plist.id)
Followings.create(user_id: ali.id, playlist_id: sundaze.id)
Followings.create(user_id: ali.id, playlist_id: pop_plist.id)
Followings.create(user_id: ali.id, playlist_id: rock_plist.id)
Followings.create(user_id: ali.id, playlist_id: minimal_plist.id)
Followings.create(user_id: ali.id, playlist_id: hip_plist.id)
Followings.create(user_id: ali.id, playlist_id: newyears.id)
Followings.create(user_id: ali.id, playlist_id: cinema_plist.id)
Followings.create(user_id: skye.id, playlist_id: sundaze.id)
Followings.create(user_id: ali.id, playlist_id: summer.id)
Followings.create(user_id: skye.id, playlist_id: minimal_plist.id)
Followings.create(user_id: skye.id, playlist_id: hip_plist.id)
Followings.create(user_id: skye.id, playlist_id: newyears.id)
Followings.create(user_id: skye.id, playlist_id: cinema_plist.id)
Followings.create(user_id: sergio.id, playlist_id: sundaze.id)
Followings.create(user_id: sergio.id, playlist_id: pop_plist.id)
Followings.create(user_id: sergio.id, playlist_id: rock_plist.id)
Followings.create(user_id: sergio.id, playlist_id: minimal_plist.id)
Followings.create(user_id: sergio.id, playlist_id: hip_plist.id)
Followings.create(user_id: sergio.id, playlist_id: newyears.id)
Followings.create(user_id: sergio.id, playlist_id: drakes.id)
Followings.create(user_id: dan.id, playlist_id: sundaze.id)
Followings.create(user_id: dan.id, playlist_id: rock_plist.id)
Followings.create(user_id: dan.id, playlist_id: newyears.id)
Followings.create(user_id: dan.id, playlist_id: cinema_plist.id)
Followings.create(user_id: dinno.id, playlist_id: sundaze.id)
Followings.create(user_id: dinno.id, playlist_id: pop_plist.id)
Followings.create(user_id: dinno.id, playlist_id: minimal_plist.id)
Followings.create(user_id: dinno.id, playlist_id: hip_plist.id)
Followings.create(user_id: john.id, playlist_id: sundaze.id)
Followings.create(user_id: john.id, playlist_id: rock_plist.id)
Followings.create(user_id: sam.id, playlist_id: sundaze.id)
Followings.create(user_id: sam.id, playlist_id: pop_plist.id)
Followings.create(user_id: jo.id, playlist_id: sundaze.id)
Followings.create(user_id: jo.id, playlist_id: minimal_plist.id)
Followings.create(user_id: jo.id, playlist_id: newyears.id)

# Making sure there is a distinct top 5 songs
summer.add_song("Tropic")
summer.add_song("Perth")
summer.add_song("The Illout")
summer.add_song("Raw")
electro_plist.add_song("Tropic")
electro_plist.add_song("Perth")
electro_plist.add_song("The Illout")
electro_plist.add_song("Raw")
sundaze.add_song("Tropic")
sundaze.add_song("Perth")
drakes.add_song("Tropic")

# Creating an original top 5 so as not to run through slow method
topsongs = {"Tropic"=>6, "Perth"=>5, "Raw"=>4, "The Illout"=>4, "Bela"=>3}
original_top_songs_playlist = Playlist.create_favourites(topsongs)